package com.example.mini4x.research

import com.example.mini4x.sim.*

object CapitalOwnershipSemanticsHarness {
    private fun emptyAdjacent(state: SimState, origin: Pos): Pos = origin.neighbours8().filter(state::inBounds).first { q -> val t=state.tile(q)!!;t.cityId==null&&t.occupantUnitId==null }
    private fun fixture(): Triple<SimState,City,City> {val state=MapGenerator.create(GameConfig(seed=5_501_991L,mapSize=MapSizeSetting.NORMAL,waterPreset=WaterPreset.DRYLANDS,gameMode=GameMode.CONQUEST,factionIds=listOf("asteria","sunspire"),humanPlayerId=0,difficulty=2));val victim=1;val original=state.players[victim].capitalCityId?.let(state::city)?:error("player 1 missing original capital");val secondPos=emptyAdjacent(state,original.pos);val secondTile=state.tile(secondPos)!!;secondTile.terrain=Terrain.FIELD;secondTile.territoryOwner=victim;secondTile.cityId=state.nextCityId;secondTile.village=false;secondTile.improvement=null;secondTile.road=false;secondTile.resource=null;secondTile.workCityId=null;val second=City(id=state.nextCityId++,owner=victim,pos=secondPos,level=1,originalOwner=victim,isCapital=false);state.cities+=second;original.owner=0;state.tile(original.pos)!!.territoryOwner=0;original.connectionPopulation=0;second.connectionPopulation=0;state.tile(original.pos)!!.road=true;secondTile.road=true;return Triple(state,original,second)}
    @JvmStatic fun main(args:Array<String>){val expectOwned=args.firstOrNull()=="expect-owned";val(state,captured,remaining)=fixture();val originalId=state.players[1].capitalCityId;check(originalId==captured.id);val resolvedBefore=state.capital(1);println("captured_capital_resolves=${resolvedBefore?.id==captured.id}");println("captured_capital_owner=${captured.owner}");DerivedState.recalculateConnections(state);println("captured_connection_population=${captured.connectionPopulation}");println("remaining_city_connection_population=${remaining.connectionPopulation}");if(expectOwned){check(resolvedBefore==null);check(captured.connectionPopulation==0);check(remaining.connectionPopulation==0);captured.owner=1;state.tile(captured.pos)!!.territoryOwner=1;val resolvedAfter=state.capital(1);check(resolvedAfter?.id==captured.id);check(state.players[1].capitalCityId==originalId);println("capital_ownership_semantics=PASS recapture_restores=true")}}
}
