package com.example.mini4x.research

import com.example.mini4x.sim.*

object DerivedStateFixedPointFuzzHarness {
    private fun commandKey(command:Command):String=when(command){is MoveUnit->"MOVE|${command.playerId}|${command.unitId}|${command.destination.x}|${command.destination.y}";is AttackUnit->"ATTACK|${command.playerId}|${command.attackerId}|${command.defenderId}";is RecoverUnit->"RECOVER|${command.playerId}|${command.unitId}";is TrainUnit->"TRAIN|${command.playerId}|${command.cityId}|${command.kind.name}";is BuyTechnology->"TECH|${command.playerId}|${command.technologyId}";is HarvestResource->"HARVEST|${command.playerId}|${command.pos.x}|${command.pos.y}";is BuildImprovement->"IMPROVE|${command.playerId}|${command.pos.x}|${command.pos.y}|${command.improvement.name}";is ChooseCityReward->"REWARD|${command.playerId}|${command.cityId}|${command.reward.name}";is CaptureCity->"CAPTURE|${command.playerId}|${command.unitId}";is ExamineRuin->"RUIN|${command.playerId}|${command.unitId}";is BuildRoad->"ROAD|${command.playerId}|${command.pos.x}|${command.pos.y}";is EstablishEmbassy->"EMBASSY|${command.playerId}|${command.targetPlayerId}";is OfferPeace->"PEACE|${command.playerId}|${command.targetPlayerId}";is BreakPeace->"BREAK_PEACE|${command.playerId}|${command.targetPlayerId}";is UpgradeShip->"UPGRADE|${command.playerId}|${command.unitId}|${command.target.name}";is GatherStarfish->"STARFISH|${command.playerId}|${command.unitId}";is SpecialAction->"SPECIAL|${command.playerId}|${command.unitId}|${command.action.name}|${command.targetPos?.x?:"_"}|${command.targetPos?.y?:"_"}";is EndTurn->"END|${command.playerId}"}
    private fun config(index:Int):GameConfig{val sizes=listOf(MapSizeSetting.TINY,MapSizeSetting.SMALL,MapSizeSetting.NORMAL,MapSizeSetting.LARGE,MapSizeSetting.HUGE);val waters=WaterPreset.entries.toList();val modes=listOf(GameMode.CONQUEST,GameMode.SCORE_30,GameMode.SCORE_RACE,GameMode.WEEKLY_20);return GameConfig(seed=7_100_003L+index*65_537L,mapSize=sizes[index%sizes.size],waterPreset=waters[(index*5+1)%waters.size],gameMode=modes[index%modes.size],factionIds=listOf("asteria","sunspire","virelia","emberhold"),humanPlayerId=0,difficulty=1+index%4,creativeEndless=false)}
    private fun choose(state:SimState,step:Int,actionsThisTurn:Int):Command{val legal=LegalCommandGenerator.all(state,state.activePlayer,includeEndTurn=true);check(legal.isNotEmpty());val end=legal.filterIsInstance<EndTurn>().first();val nonEnd=legal.filterNot{it is EndTurn}.sortedBy(::commandKey);if(actionsThisTurn>=4||nonEnd.isEmpty())return end;val index=Math.floorMod(step*73L+state.roundNumber*29L+state.activePlayer*13L,nonEnd.size.toLong()).toInt();return nonEnd[index]}
    private fun assertFixedPoint(state:SimState,label:String){val before=GameStateCodec.encode(state);val firstEvents=mutableListOf<SimEvent>();DerivedState.recalculateAll(state,firstEvents);val afterFirst=GameStateCodec.encode(state);check(afterFirst==before){"$label derived state changed after CommandEngine had already recalculated it\nevents=$firstEvents"};val secondEvents=mutableListOf<SimEvent>();DerivedState.recalculateAll(state,secondEvents);val afterSecond=GameStateCodec.encode(state);check(afterSecond==afterFirst);val transitionTypes=setOf(EventType.CITY_UPGRADED,EventType.PLAYER_ELIMINATED,EventType.SCORE_CHANGED,EventType.VICTORY);check(firstEvents.none{it.type in transitionTypes});check(secondEvents.none{it.type in transitionTypes})}
    @JvmStatic fun main(args:Array<String>){val scenarios=args.getOrNull(0)?.toIntOrNull()?.coerceIn(1,100)?:16;val steps=args.getOrNull(1)?.toIntOrNull()?.coerceIn(10,10_000)?:500;var commands=0;var probes=0;repeat(scenarios){scenario->val state=MapGenerator.create(config(scenario));assertFixedPoint(state,"scenario-$scenario/initial");var actionsThisTurn=0;var observed=state.activePlayer;var step=0;while(!state.finished&&step<steps){if(state.activePlayer!=observed){observed=state.activePlayer;actionsThisTurn=0};val command=choose(state,step,actionsThisTurn);val result=CommandEngine.execute(state,command);check(result.accepted){"scenario=$scenario step=$step rejected ${commandKey(command)} :: ${result.reason}"};SimInvariantAudit.assertValid(state,"fixed-point/$scenario/$step");assertFixedPoint(state,"scenario-$scenario/post-$step/${commandKey(command)}");probes++;commands++;actionsThisTurn=if(command is EndTurn)0 else actionsThisTurn+1;step++};println("derived_fixed_point_scenario=$scenario commands=$step finished=${state.finished} round=${state.roundNumber}")};println("derived_state_fixed_point=PASS scenarios=$scenarios commands=$commands probes=$probes")}
}
