package com.example.mini4x.research

import com.example.mini4x.sim.*

object LegalCommandBranchFuzzHarness {
 private fun key(c:Command)=when(c){is MoveUnit->"MOVE|${c.playerId}|${c.unitId}|${c.destination.x}|${c.destination.y}";is AttackUnit->"ATTACK|${c.playerId}|${c.attackerId}|${c.defenderId}";is RecoverUnit->"RECOVER|${c.playerId}|${c.unitId}";is TrainUnit->"TRAIN|${c.playerId}|${c.cityId}|${c.kind.name}";is BuyTechnology->"TECH|${c.playerId}|${c.technologyId}";is HarvestResource->"HARVEST|${c.playerId}|${c.pos.x}|${c.pos.y}";is BuildImprovement->"IMPROVE|${c.playerId}|${c.pos.x}|${c.pos.y}|${c.improvement.name}";is ChooseCityReward->"REWARD|${c.playerId}|${c.cityId}|${c.reward.name}";is CaptureCity->"CAPTURE|${c.playerId}|${c.unitId}";is ExamineRuin->"RUIN|${c.playerId}|${c.unitId}";is BuildRoad->"ROAD|${c.playerId}|${c.pos.x}|${c.pos.y}";is EstablishEmbassy->"EMBASSY|${c.playerId}|${c.targetPlayerId}";is OfferPeace->"PEACE|${c.playerId}|${c.targetPlayerId}";is BreakPeace->"BREAK_PEACE|${c.playerId}|${c.targetPlayerId}";is UpgradeShip->"UPGRADE|${c.playerId}|${c.unitId}|${c.target.name}";is GatherStarfish->"STARFISH|${c.playerId}|${c.unitId}";is SpecialAction->"SPECIAL|${c.playerId}|${c.unitId}|${c.action.name}|${c.targetPos?.x?:"_"}|${c.targetPos?.y?:"_"}";is EndTurn->"END|${c.playerId}"}
 private fun family(c:Command)=when(c){is MoveUnit->"move";is AttackUnit->"attack";is RecoverUnit->"recover";is TrainUnit->"train";is BuyTechnology->"technology";is HarvestResource->"harvest";is BuildImprovement->"improvement";is ChooseCityReward->"city_reward";is CaptureCity->"capture";is ExamineRuin->"ruin";is BuildRoad->"road";is EstablishEmbassy->"embassy";is OfferPeace->"peace_offer";is BreakPeace->"peace_break";is UpgradeShip->"ship_upgrade";is GatherStarfish->"starfish";is SpecialAction->"special_${c.action.name.lowercase()}";is EndTurn->"end_turn"}
 private fun branchCheck(base:SimState,step:Int,coverage:MutableMap<String,Int>):Int{val legal=LegalCommandGenerator.all(base,base.activePlayer,true);val selected=legal.groupBy(::family).toSortedMap().flatMap{(_,commands)->commands.sortedBy(::key).let{if(it.size<=2)it else listOf(it.first(),it.last())}};var branches=0;for(command in selected){val copy=base.deepCopy();val serial=copy.actionSerial;val result=CommandEngine.execute(copy,command);check(result.accepted){"branch step=$step rejected ${key(command)} :: ${result.reason}"};check(copy.actionSerial==serial+1);SimInvariantAudit.assertValid(copy,"branch-$step/${key(command)}");val encoded=GameStateCodec.encode(copy);val decoded=GameStateCodec.decode(encoded);check(GameStateCodec.encode(decoded)==encoded);val f=family(command);coverage[f]=(coverage[f]?:0)+1;branches++};return branches}
 private fun advance(base:SimState,step:Int,actions:Int):Command{val legal=LegalCommandGenerator.all(base,base.activePlayer,true);val end=legal.filterIsInstance<EndTurn>().first();val non=legal.filterNot{it is EndTurn}.sortedBy(::key);if(actions>=3||non.isEmpty())return end;val index=Math.floorMod(step*53L+base.roundNumber*19L+base.activePlayer*11L,non.size.toLong()).toInt();return non[index]}
 private fun config(index:Int):GameConfig{val sizes=listOf(MapSizeSetting.TINY,MapSizeSetting.SMALL,MapSizeSetting.NORMAL,MapSizeSetting.LARGE,MapSizeSetting.HUGE);val modes=listOf(GameMode.CONQUEST,GameMode.SCORE_30,GameMode.WEEKLY_20);val waters=WaterPreset.entries.toList();return GameConfig(seed=880_001L+index*12_289L,mapSize=sizes[index%sizes.size],waterPreset=waters[(index*2+1)%waters.size],gameMode=modes[index%modes.size],factionIds=listOf("asteria","sunspire","virelia","emberhold"),humanPlayerId=0,difficulty=1+index%4,creativeEndless=false)}
 @JvmStatic fun main(args:Array<String>){val scenarios=args.getOrNull(0)?.toIntOrNull()?.coerceIn(1,64)?:10;val steps=args.getOrNull(1)?.toIntOrNull()?.coerceIn(10,5000)?:160;val interval=args.getOrNull(2)?.toIntOrNull()?.coerceIn(1,50)?:4;val coverage=sortedMapOf<String,Int>();var branches=0;var trajectory=0;repeat(scenarios){scenario->val state=MapGenerator.create(config(scenario));SimInvariantAudit.assertValid(state,"scenario-$scenario/initial");var actions=0;var observed=state.activePlayer;var step=0;while(!state.finished&&step<steps){if(state.activePlayer!=observed){observed=state.activePlayer;actions=0};if(step%interval==0)branches+=branchCheck(state,step,coverage);val c=advance(state,step,actions);val result=CommandEngine.execute(state,c);check(result.accepted){"trajectory scenario=$scenario step=$step rejected ${key(c)} :: ${result.reason}"};SimInvariantAudit.assertValid(state,"scenario-$scenario/post-$step");actions=if(c is EndTurn)0 else actions+1;step++;trajectory++};println("branch_scenario=$scenario trajectory=$step finished=${state.finished} rounds=${state.roundNumber}")};println("legal_command_branch_fuzz=PASS scenarios=$scenarios trajectory=$trajectory branches=$branches coverage=$coverage")}
}
