package com.example.mini4x.research

import com.example.mini4x.sim.*
import java.security.MessageDigest

object SaveResumeEquivalenceHarness {
 private fun digest(state:SimState)=MessageDigest.getInstance("SHA-256").digest(GameStateCodec.encode(state).toByteArray()).joinToString(""){"%02x".format(it)}
 private fun key(c:Command)=when(c){is MoveUnit->"MOVE|${c.playerId}|${c.unitId}|${c.destination.x}|${c.destination.y}";is AttackUnit->"ATTACK|${c.playerId}|${c.attackerId}|${c.defenderId}";is RecoverUnit->"RECOVER|${c.playerId}|${c.unitId}";is TrainUnit->"TRAIN|${c.playerId}|${c.cityId}|${c.kind.name}";is BuyTechnology->"TECH|${c.playerId}|${c.technologyId}";is HarvestResource->"HARVEST|${c.playerId}|${c.pos.x}|${c.pos.y}";is BuildImprovement->"IMPROVE|${c.playerId}|${c.pos.x}|${c.pos.y}|${c.improvement.name}";is ChooseCityReward->"REWARD|${c.playerId}|${c.cityId}|${c.reward.name}";is CaptureCity->"CAPTURE|${c.playerId}|${c.unitId}";is ExamineRuin->"RUIN|${c.playerId}|${c.unitId}";is BuildRoad->"ROAD|${c.playerId}|${c.pos.x}|${c.pos.y}";is EstablishEmbassy->"EMBASSY|${c.playerId}|${c.targetPlayerId}";is OfferPeace->"PEACE|${c.playerId}|${c.targetPlayerId}";is BreakPeace->"BREAK_PEACE|${c.playerId}|${c.targetPlayerId}";is UpgradeShip->"UPGRADE|${c.playerId}|${c.unitId}|${c.target.name}";is GatherStarfish->"STARFISH|${c.playerId}|${c.unitId}";is SpecialAction->"SPECIAL|${c.playerId}|${c.unitId}|${c.action.name}|${c.targetPos?.x?:"_"}|${c.targetPos?.y?:"_"}";is EndTurn->"END|${c.playerId}"}
 private fun choose(state:SimState,step:Int,actions:Int):Command{val legal=LegalCommandGenerator.all(state,state.activePlayer,true);check(legal.isNotEmpty());val end=legal.filterIsInstance<EndTurn>().first();val non=legal.filterNot{it is EndTurn}.sortedBy(::key);if(actions>=4||non.isEmpty())return end;val index=Math.floorMod(step*37L+state.roundNumber*17L+state.activePlayer*13L,non.size.toLong()).toInt();return non[index]}
 private fun configs(count:Int):List<GameConfig>{val sizes=listOf(MapSizeSetting.TINY,MapSizeSetting.SMALL,MapSizeSetting.NORMAL,MapSizeSetting.LARGE);val waters=WaterPreset.entries.toList();val modes=listOf(GameMode.CONQUEST,GameMode.SCORE_30,GameMode.WEEKLY_20);return(0 until count).map{i->GameConfig(seed=700_001L+7_919L*i,mapSize=sizes[i%sizes.size],waterPreset=waters[(i*5)%waters.size],gameMode=modes[i%modes.size],factionIds=listOf("asteria","sunspire","virelia","emberhold"),humanPlayerId=0,difficulty=1+i%4,creativeEndless=false)}}
 private fun run(config:GameConfig,max:Int,label:String):Int{var continuous=MapGenerator.create(config);var resumed=GameStateCodec.decode(GameStateCodec.encode(continuous));check(GameStateCodec.encode(continuous)==GameStateCodec.encode(resumed));SimInvariantAudit.assertValid(continuous,"$label/initial-continuous");SimInvariantAudit.assertValid(resumed,"$label/initial-resumed");var actions=0;var observed=continuous.activePlayer;var step=0;while(!continuous.finished&&step<max){if(continuous.activePlayer!=observed){observed=continuous.activePlayer;actions=0};resumed=GameStateCodec.decode(GameStateCodec.encode(resumed));check(digest(continuous)==digest(resumed));val command=choose(continuous,step,actions);check(CommandEngine.validate(resumed,command)==null){"$label step=$step command legal continuously but illegal after resume: ${key(command)}"};val a=CommandEngine.execute(continuous,command);val b=CommandEngine.execute(resumed,command);check(a.accepted&&b.accepted);check(a.events==b.events){"$label step=$step event divergence"};check(GameStateCodec.encode(continuous)==GameStateCodec.encode(resumed)){"$label step=$step state divergence"};SimInvariantAudit.assertValid(continuous,"$label/post-$step");actions=if(command is EndTurn)0 else actions+1;step++};check(continuous.finished==resumed.finished&&continuous.winnerId==resumed.winnerId);println("resume_scenario=$label commands=$step rounds=${continuous.roundNumber} finished=${continuous.finished} digest=${digest(continuous).take(16)}");return step}
 @JvmStatic fun main(args:Array<String>){val count=args.getOrNull(0)?.toIntOrNull()?.coerceIn(1,64)?:8;val max=args.getOrNull(1)?.toIntOrNull()?.coerceIn(20,10_000)?:300;var total=0;configs(count).forEachIndexed{i,cfg->total+=run(cfg,max,"scenario-$i")};println("save_resume_equivalence=PASS scenarios=$count commands=$total")}
}
