package com.example.mini4x.research

import com.example.mini4x.sim.*

object SimInvariantAudit {
    fun assertValid(state: SimState, label: String = "state") {
        fun fail(message: String): Nothing = error("$label: $message")
        if(state.size<=0)fail("non-positive map size ${state.size}");if(state.map.size!=state.size)fail("map outer size ${state.map.size} != ${state.size}")
        state.map.forEachIndexed{x,column->if(column.size!=state.size)fail("map column $x size ${column.size} != ${state.size}");column.forEachIndexed{y,tile->if(tile.pos!=Pos(x,y))fail("tile coordinate mismatch at $x,$y: ${tile.pos}")}}
        if(state.players.isEmpty())fail("no players")
        state.players.forEachIndexed{index,player->if(player.id!=index)fail("player index/id mismatch: index=$index id=${player.id}");if(player.stars<0)fail("player ${player.id} has negative stars ${player.stars}");player.capitalCityId?.let{id->val city=state.city(id)?:fail("player ${player.id} capitalCityId $id is missing");if(!city.isCapital)fail("player ${player.id} capitalCityId $id does not point to a capital city")};player.metPlayers.forEach{other->if(other !in state.players.indices||other==player.id)fail("player ${player.id} has invalid met-player $other")};player.embassies.forEach{other->if(other !in state.players.indices||other==player.id)fail("player ${player.id} has invalid embassy target $other")}}
        if(state.activePlayer !in state.players.indices)fail("invalid activePlayer ${state.activePlayer}");if(!state.finished&&state.players[state.activePlayer].eliminated)fail("active player ${state.activePlayer} is eliminated")
        if(state.diplomacy.size!=state.players.size)fail("diplomacy row count mismatch");for(a in state.players.indices){if(state.diplomacy[a].size!=state.players.size)fail("diplomacy column count mismatch for $a");for(b in state.players.indices)if(state.diplomacy[a][b]!=state.diplomacy[b][a])fail("asymmetric diplomacy $a/$b")}
        val cityIds=state.cities.map{it.id};if(cityIds.size!=cityIds.toSet().size)fail("duplicate city ids");val unitIds=state.units.map{it.id};if(unitIds.size!=unitIds.toSet().size)fail("duplicate unit ids");val maxCityId=cityIds.maxOrNull()?:0;val maxUnitId=unitIds.maxOrNull()?:0;if(state.nextCityId<=maxCityId)fail("nextCityId ${state.nextCityId} <= existing max $maxCityId");if(state.nextUnitId<=maxUnitId)fail("nextUnitId ${state.nextUnitId} <= existing max $maxUnitId")
        state.cities.forEach{city->if(city.owner !in state.players.indices)fail("city ${city.id} invalid owner ${city.owner}");if(!state.inBounds(city.pos))fail("city ${city.id} out of bounds at ${city.pos}");val tile=state.tile(city.pos)?:fail("city ${city.id} has no tile");if(tile.cityId!=city.id)fail("city ${city.id} tile points to ${tile.cityId}");if(city.level<1)fail("city ${city.id} invalid level ${city.level}");if(city.basePopulation<0||city.buildingPopulation<0||city.connectionPopulation<0||city.spentPopulation<0)fail("city ${city.id} has negative population component");city.besiegedByUnitId?.let{unitId->val unit=state.unit(unitId)?:fail("city ${city.id} besieged by missing unit $unitId");if(unit.owner==city.owner)fail("city ${city.id} besieged by friendly unit $unitId");if(unit.pos!=city.pos)fail("city ${city.id} besieger $unitId not on city tile")};city.supportedUnitIds.forEach{unitId->val unit=state.unit(unitId)?:fail("city ${city.id} supports missing unit $unitId");if(unit.supportCityId!=city.id)fail("city ${city.id} supports unit $unitId but unit supportCityId=${unit.supportCityId}")}}
        val occupied=mutableSetOf<Pos>();state.units.forEach{unit->if(unit.owner !in state.players.indices)fail("unit ${unit.id} invalid owner ${unit.owner}");if(!state.inBounds(unit.pos))fail("unit ${unit.id} out of bounds at ${unit.pos}");if(!occupied.add(unit.pos))fail("multiple units occupy ${unit.pos}");val tile=state.tile(unit.pos)?:fail("unit ${unit.id} has no tile");if(tile.occupantUnitId!=unit.id)fail("unit ${unit.id} tile occupant is ${tile.occupantUnitId}");if(unit.hp<=0)fail("live unit ${unit.id} has hp=${unit.hp}");if(unit.frozenTurns<0)fail("unit ${unit.id} has negative frozenTurns ${unit.frozenTurns}");unit.supportCityId?.let{cityId->val city=state.city(cityId)?:fail("unit ${unit.id} support city $cityId missing");if(unit.id !in city.supportedUnitIds)fail("unit ${unit.id} points to city $cityId but city does not support it")}}
        for(x in 0 until state.size)for(y in 0 until state.size){val tile=state.map[x][y];tile.territoryOwner?.let{if(it !in state.players.indices)fail("tile ${tile.pos} invalid territory owner $it")};tile.cityId?.let{cityId->val city=state.city(cityId)?:fail("tile ${tile.pos} points to missing city $cityId");if(city.pos!=tile.pos)fail("tile ${tile.pos} cityId=$cityId but city is at ${city.pos}")};tile.workCityId?.let{state.city(it)?:fail("tile ${tile.pos} workCityId $it missing")};tile.occupantUnitId?.let{unitId->val unit=state.unit(unitId)?:fail("tile ${tile.pos} occupant $unitId missing");if(unit.pos!=tile.pos)fail("tile ${tile.pos} occupant $unitId is at ${unit.pos}")}}
        if(state.discoveredTiles.size!=state.players.size)fail("discoveredTiles/player count mismatch");state.discoveredTiles.forEachIndexed{pid,set->set.forEach{if(!state.inBounds(it))fail("player $pid discovered out-of-bounds $it")}};if(state.score.size!=state.players.size)fail("score/player count mismatch");if(state.score.any{it<0})fail("negative score present: ${state.score}")
        if(state.finished){val winner=state.winnerId?:fail("finished state has no winner");if(winner !in state.players.indices)fail("invalid winnerId $winner")}else if(state.winnerId!=null)fail("unfinished state already has winnerId ${state.winnerId}")
    }
}
