package com.example.mini4x.research

import com.example.mini4x.sim.*

object SimulationEdgeCaseFixtures {
    private fun base(mode: GameMode = GameMode.CONQUEST, seed: Long = 44_041L): SimState = MapGenerator.create(GameConfig(seed=seed,mapSize=MapSizeSetting.TINY,waterPreset=WaterPreset.CONTINENTS,gameMode=mode,factionIds=listOf("asteria","sunspire"),humanPlayerId=0,difficulty=2,creativeEndless=false))
    private fun placeUnit(state: SimState, unit: UnitState, pos: Pos) {state.tile(unit.pos)?.takeIf { it.occupantUnitId == unit.id }?.occupantUnitId = null;state.tile(pos)?.occupantUnitId?.let { otherId -> if (otherId != unit.id) {val other = state.unit(otherId);if (other != null) {val fallback=(0 until state.size).asSequence().flatMap{x->(0 until state.size).asSequence().map{y->Pos(x,y)}}.first{q->q!=pos&&state.tile(q)?.occupantUnitId==null};state.tile(other.pos)?.takeIf{it.occupantUnitId==other.id}?.occupantUnitId=null;other.pos=fallback;state.tile(fallback)!!.occupantUnitId=other.id}}};unit.pos=pos;state.tile(pos)!!.occupantUnitId=unit.id}
    private fun convertDetachesSupport(expectClean:Boolean):Boolean {val state=base(seed=44_101L);state.activePlayer=0;val attacker=state.ownedUnits(0).first();val defender=state.ownedUnits(1).first();val support=defender.supportCityId?.let(state::city)?:state.ownedCities(1).first().also{city->defender.supportCityId=city.id;city.supportedUnitIds+=defender.id};support.supportedUnitIds+=defender.id;attacker.kind=UnitKind.MIND_BENDER;attacker.moved=false;attacker.attacked=false;attacker.tookAction=false;placeUnit(state,attacker,Pos(4,4));placeUnit(state,defender,Pos(5,4));state.diplomacy[0][1]=Relation.WAR;state.diplomacy[1][0]=Relation.WAR;val result=CommandEngine.execute(state,AttackUnit(0,attacker.id,defender.id));check(result.accepted){"convert fixture attack rejected: ${result.reason}"};check(defender.owner==0&&defender.supportCityId==null&&defender.independent);val stale=defender.id in support.supportedUnitIds;if(expectClean)check(!stale);return stale}
    private fun eliminationCleansReferences(expectClean:Boolean):Pair<Boolean,Boolean>{val state=base(seed=44_202L);val victim=1;val unit=state.ownedUnits(victim).first();val formerCity=state.ownedCities(victim).first();unit.supportCityId=formerCity.id;formerCity.supportedUnitIds+=unit.id;formerCity.owner=0;placeUnit(state,unit,formerCity.pos);formerCity.besiegedByUnitId=unit.id;check(state.ownedCities(victim).isEmpty());val events=mutableListOf<SimEvent>();DerivedState.checkElimination(state,events);check(state.players[victim].eliminated);check(state.unit(unit.id)==null);val staleSupport=state.cities.any{unit.id in it.supportedUnitIds};val staleSiege=state.cities.any{it.besiegedByUnitId==unit.id};if(expectClean){check(!staleSupport);check(!staleSiege)};return staleSupport to staleSiege}
    private fun peaceClearsSiege(expectClean:Boolean):Boolean{val state=base(seed=44_303L);state.activePlayer=0;val attacker=state.ownedUnits(0).first();val city=state.ownedCities(1).first();state.players[0].technologies+="strategy";state.diplomacy[0][1]=Relation.WAR;state.diplomacy[1][0]=Relation.WAR;placeUnit(state,attacker,city.pos);city.besiegedByUnitId=attacker.id;val result=CommandEngine.execute(state,OfferPeace(0,1));check(result.accepted);val stale=city.besiegedByUnitId==attacker.id;if(expectClean)check(!stale);return stale}
    private fun timedScoreIgnoresEliminated(mode:GameMode,terminalRound:Int,expectClean:Boolean):Int?{val state=base(mode,44_404L+terminalRound);state.roundNumber=terminalRound;state.finished=false;state.winnerId=null;state.victoryReason="";state.players[0].eliminated=false;state.players[1].eliminated=true;state.score[0]=100;state.score[1]=50_000;state.cities.filter{it.owner==1}.forEach{it.owner=0};DerivedState.checkVictory(state,mutableListOf());if(expectClean)check(state.winnerId==0);return state.winnerId}
    @JvmStatic fun main(args:Array<String>){val expectClean=args.firstOrNull()=="expect-clean";val convertStale=convertDetachesSupport(expectClean);val(eliminationSupport,eliminationSiege)=eliminationCleansReferences(expectClean);val peaceSiege=peaceClearsSiege(expectClean);val score30Winner=timedScoreIgnoresEliminated(GameMode.SCORE_30,31,expectClean);val weeklyWinner=timedScoreIgnoresEliminated(GameMode.WEEKLY_20,21,expectClean);println("convert_stale_support=$convertStale");println("elimination_stale_support=$eliminationSupport");println("elimination_stale_siege=$eliminationSiege");println("peace_stale_siege=$peaceSiege");println("score30_winner=$score30Winner");println("weekly20_winner=$weeklyWinner");if(expectClean)println("simulation_edge_cases=PASS")}
}
