package com.example.mini4x.research

import com.example.mini4x.sim.*
import java.security.MessageDigest

private data class FuzzResult(val finalDigest:String,val traceDigest:String,val acceptedCommands:Int,val rounds:Int,val finished:Boolean,val coverage:Map<String,Int>)
private class FuzzPicker(seed:Long){private var state=seed;fun nextIndex(bound:Int):Int{require(bound>0);state+=-7046029254386353131L;var z=state;z=(z xor(z ushr 30))*-4658895280553007687L;z=(z xor(z ushr 27))*-7723592293110705685L;z=z xor(z ushr 31);return((z and Long.MAX_VALUE)%bound).toInt()}}
object SimulationFuzzHarness {
 private fun sha256(text:String)=MessageDigest.getInstance("SHA-256").digest(text.toByteArray()).joinToString(""){"%02x".format(it)}
 private fun stateDigest(state:SimState)=sha256(GameStateCodec.encode(state))
 private fun commandKey(c:Command)=when(c){is MoveUnit->"MOVE|${c.playerId}|${c.unitId}|${c.destination.x}|${c.destination.y}";is AttackUnit->"ATTACK|${c.playerId}|${c.attackerId}|${c.defenderId}";is RecoverUnit->"RECOVER|${c.playerId}|${c.unitId}";is TrainUnit->"TRAIN|${c.playerId}|${c.cityId}|${c.kind.name}";is BuyTechnology->"TECH|${c.playerId}|${c.technologyId}";is HarvestResource->"HARVEST|${c.playerId}|${c.pos.x}|${c.pos.y}";is BuildImprovement->"IMPROVE|${c.playerId}|${c.pos.x}|${c.pos.y}|${c.improvement.name}";is ChooseCityReward->"REWARD|${c.playerId}|${c.cityId}|${c.reward.name}";is CaptureCity->"CAPTURE|${c.playerId}|${c.unitId}";is ExamineRuin->"RUIN|${c.playerId}|${c.unitId}";is BuildRoad->"ROAD|${c.playerId}|${c.pos.x}|${c.pos.y}";is EstablishEmbassy->"EMBASSY|${c.playerId}|${c.targetPlayerId}";is OfferPeace->"PEACE|${c.playerId}|${c.targetPlayerId}";is BreakPeace->"BREAK_PEACE|${c.playerId}|${c.targetPlayerId}";is UpgradeShip->"UPGRADE|${c.playerId}|${c.unitId}|${c.target.name}";is GatherStarfish->"STARFISH|${c.playerId}|${c.unitId}";is SpecialAction->"SPECIAL|${c.playerId}|${c.unitId}|${c.action.name}|${c.targetPos?.x?:"_"}|${c.targetPos?.y?:"_"}";is EndTurn->"END|${c.playerId}"}
 private fun family(c:Command)=when(c){is MoveUnit->"move";is AttackUnit->"attack";is RecoverUnit->"recover";is TrainUnit->"train";is BuyTechnology->"technology";is HarvestResource->"harvest";is BuildImprovement->"improvement";is ChooseCityReward->"city_reward";is CaptureCity->"capture";is ExamineRuin->"ruin";is BuildRoad->"road";is EstablishEmbassy->"embassy";is OfferPeace->"peace_offer";is BreakPeace->"peace_break";is UpgradeShip->"ship_upgrade";is GatherStarfish->"starfish";is SpecialAction->"special_${c.action.name.lowercase()}";is EndTurn->"end_turn"}
 private fun roundTrip(state:SimState,label:String){val e=GameStateCodec.encode(state);val d=GameStateCodec.decode(e);SimInvariantAudit.assertValid(d,"$label/decoded");check(GameStateCodec.encode(d)==e)}
 private fun rejectedDoesNotMutate(state:SimState,label:String){if(state.players.size<2||state.finished)return;val wrong=(state.activePlayer+1)%state.players.size;val before=GameStateCodec.encode(state);val result=CommandEngine.execute(state,EndTurn(wrong));check(!result.accepted);check(GameStateCodec.encode(state)==before){"$label rejected command mutated state"}}
 private fun choose(state:SimState,picker:FuzzPicker,actionsThisTurn:Int):Command{val legal=LegalCommandGenerator.all(state,state.activePlayer,true);check(legal.isNotEmpty());val end=legal.filterIsInstance<EndTurn>().firstOrNull()?:EndTurn(state.activePlayer);val non=legal.filterNot{it is EndTurn};if(actionsThisTurn>=4||non.isEmpty())return end;val groups=non.groupBy(::family).toSortedMap();val names=groups.keys.toList();val name=names[picker.nextIndex(names.size)];val options=groups.getValue(name).sortedBy(::commandKey);return options[picker.nextIndex(options.size)]}
 private fun runOne(config:GameConfig,pickerSeed:Long,maxCommands:Int,label:String):FuzzResult{val state=MapGenerator.create(config);SimInvariantAudit.assertValid(state,"$label/initial");roundTrip(state,"$label/initial");val picker=FuzzPicker(pickerSeed);val trace=StringBuilder();val coverage=sortedMapOf<String,Int>();var accepted=0;var actions=0;var observed=state.activePlayer;while(!state.finished&&accepted<maxCommands){SimInvariantAudit.assertValid(state,"$label/pre-$accepted");if(state.activePlayer!=observed){observed=state.activePlayer;actions=0};if(accepted%11==0)rejectedDoesNotMutate(state,"$label/reject-$accepted");if(accepted%17==0)roundTrip(state,"$label/save-$accepted");val c=choose(state,picker,actions);val key=commandKey(c);val serial=state.actionSerial;val result=CommandEngine.execute(state,c);check(result.accepted){"$label step=$accepted rejected $key :: ${result.reason}"};check(state.actionSerial==serial+1);trace.append(key).append('\n');val f=family(c);coverage[f]=(coverage[f]?:0)+1;accepted++;actions=if(c is EndTurn)0 else actions+1;SimInvariantAudit.assertValid(state,"$label/post-$accepted/$key")};roundTrip(state,"$label/final");return FuzzResult(stateDigest(state),sha256(trace.toString()),accepted,state.roundNumber,state.finished,coverage)}
 private fun configs(count:Int):List<GameConfig>{val sizes=listOf(MapSizeSetting.TINY,MapSizeSetting.SMALL,MapSizeSetting.NORMAL,MapSizeSetting.LARGE,MapSizeSetting.HUGE,MapSizeSetting.MASSIVE);val waters=WaterPreset.entries.toList();val modes=listOf(GameMode.CONQUEST,GameMode.SCORE_30);val factions=listOf("asteria","sunspire","virelia","emberhold");return(0 until count).map{i->GameConfig(seed=91_337L+i*10_007L,mapSize=sizes[i%sizes.size],waterPreset=waters[(i*3)%waters.size],gameMode=modes[i%modes.size],factionIds=factions,humanPlayerId=0,difficulty=1+(i%4),creativeEndless=false)}}
 @JvmStatic fun main(args:Array<String>){val count=args.getOrNull(0)?.toIntOrNull()?.coerceIn(1,128)?:12;val max=args.getOrNull(1)?.toIntOrNull()?.coerceIn(20,20_000)?:400;val aggregate=sortedMapOf<String,Int>();var total=0;var finished=0;configs(count).forEachIndexed{i,cfg->val seed=cfg.seed xor 0x51A7E5EEDL;val a=runOne(cfg,seed,max,"scenario-$i/A");val b=runOne(cfg,seed,max,"scenario-$i/B");check(a.finalDigest==b.finalDigest);check(a.traceDigest==b.traceDigest);check(a.acceptedCommands==b.acceptedCommands);a.coverage.forEach{(f,n)->aggregate[f]=(aggregate[f]?:0)+n};total+=a.acceptedCommands;if(a.finished)finished++;println("scenario=$i commands=${a.acceptedCommands} rounds=${a.rounds} finished=${a.finished}")};println("simulation_fuzz=PASS scenarios=$count commands=$total finished=$finished coverage=$aggregate")}
}
