import { Difficulty, GameMode, PerformanceMetrics, QuestionAttempt } from '../../types';

const difficultyMultiplier: Record<Difficulty, number> = { beginner: 1, intermediate: 1.2, advanced: 1.5 };
const modeMultiplier: Record<GameMode, number> = { practice: 1, quickSprint: 1, fixed25: 1.1, survival: 1.15, adaptive: 1.1, bossRound: 1.35, mistakeWorkout: 1.1, dailyChallenge: 1.2 };
export const levelThresholds = [0, 100, 250, 450, 700, 1000, 1350, 1750, 2200, 2700, 3250, 3850, 4500, 5200, 5950];
export function getLevelFromXp(totalXp: number): number { let level = 1; for (let i = 0; i < levelThresholds.length; i += 1) if (totalXp >= (levelThresholds[i] ?? 0)) level = i + 1; return level; }
export function calculateQuestionXp(params: { isCorrect: boolean; difficulty: Difficulty; mode: GameMode; timeToAnswerMs: number; answerStreak: number; isMistakeCorrection?: boolean; isWeakTopic?: boolean }): number { const base = params.isCorrect ? 10 : 1; let xp = base * difficultyMultiplier[params.difficulty] * modeMultiplier[params.mode]; if (['quickSprint','fixed25','survival','bossRound'].includes(params.mode) && params.isCorrect) xp += params.timeToAnswerMs < 3000 ? 4 : params.timeToAnswerMs < 6000 ? 2 : 0; if (params.isCorrect && params.answerStreak >= 5) xp += 5; else if (params.isCorrect && params.answerStreak >= 3) xp += 3; if (params.isMistakeCorrection && params.isCorrect) xp += 5; if (params.isWeakTopic && params.isCorrect) xp += 2; return Math.round(xp); }
export function calculateQuestionScore(params: { isCorrect: boolean; mode: GameMode; timeToAnswerMs: number; answerStreak: number }): number { if (!params.isCorrect) return 0; if (!['quickSprint','fixed25','survival','bossRound'].includes(params.mode)) return 100; const speedBonus = params.timeToAnswerMs < 3000 ? 40 : params.timeToAnswerMs < 6000 ? 20 : 0; const streakBonus = Math.min(50, Math.max(0, params.answerStreak - 1) * 10); return 100 + speedBonus + streakBonus; }
function median(values: number[]): number { if (!values.length) return 0; const sorted = [...values].sort((a,b)=>a-b); const middle = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[middle]! : Math.round(((sorted[middle-1] ?? 0) + (sorted[middle] ?? 0)) / 2); }
export function calculatePerformanceMetrics(attempts: QuestionAttempt[], difficulty: Difficulty): PerformanceMetrics { if (!attempts.length) return { accuracy:0, medianAnswerTimeMs:0, questionsPerMinute:0, consistency:0, mathRating:0 }; const correct = attempts.filter(a=>a.isCorrect); const accuracy = (correct.length / attempts.length) * 100; const times = correct.map(a=>Math.max(250,a.timeToAnswerMs)); const medianAnswerTimeMs = median(times); const totalTimeMs = attempts.reduce((sum,a)=>sum+Math.max(250,a.timeToAnswerMs),0); const questionsPerMinute = totalTimeMs > 0 ? (attempts.length * 60000) / totalTimeMs : 0; const mean = times.length ? times.reduce((s,v)=>s+v,0)/times.length : 0; const deviation = times.length ? Math.sqrt(times.reduce((s,v)=>s+(v-mean)**2,0)/times.length) : 0; const consistency = mean > 0 ? Math.max(0,Math.min(100,100-(deviation/mean)*100)) : 0; const accuracyGate = accuracy < 60 ? accuracy/100 : 0.6 + ((accuracy-60)/40)*0.4; const speedScore = medianAnswerTimeMs > 0 ? Math.max(0,Math.min(100,120-medianAnswerTimeMs/55)) : 0; const difficultyScore = difficulty === 'advanced' ? 100 : difficulty === 'intermediate' ? 75 : 55; const raw = speedScore*0.5 + accuracy*0.35 + difficultyScore*0.15; const mathRating = Math.round(Math.max(0,Math.min(1000,raw*10*accuracyGate))); return { accuracy:Math.round(accuracy), medianAnswerTimeMs, questionsPerMinute:Number(questionsPerMinute.toFixed(1)), consistency:Math.round(consistency), mathRating }; }
export function summarizeAttempts(attempts: QuestionAttempt[]) { const correctCount = attempts.filter(a=>a.isCorrect).length; const wrongCount = attempts.length - correctCount; const xpEarned = attempts.reduce((s,a)=>s+a.xpEarned,0); const score = attempts.reduce((s,a)=>s+a.scoreEarned,0); return { correctCount, wrongCount, xpEarned, score, accuracy: attempts.length ? Math.round((correctCount/attempts.length)*100) : 0 }; }
