import { Difficulty, Question, QuestionSource, SubjectId } from '../../types';
import { subjectIds } from '../../data/subjects';
import { compareFractions, formatFraction, Fraction, simplifyFraction } from './fractions';
import { createRandom, makeSeed, Random } from './random';

type GenerateOptions = { seed?: string; source?: QuestionSource; level?: number };
const difficultyRank: Record<Difficulty, number> = { beginner: 1, intermediate: 2, advanced: 3 };
function rangeByDifficulty(d:Difficulty,b:number,i:number,a:number){return d==='beginner'?b:d==='intermediate'?i:a;}
function buildQuestion(params:{seed:string;subject:SubjectId;difficulty:Difficulty;prompt:string;spokenPrompt?:string;correctAnswer:string;acceptedAnswers?:string[];explanation:string;tags:string[];metadata?:Record<string,number|string|boolean>;inputType?:Question['inputType'];source?:QuestionSource}):Question{const q:Question={id:`${params.subject}-${params.difficulty}-${params.seed}`,seed:params.seed,subject:params.subject,difficulty:params.difficulty,prompt:params.prompt,spokenPrompt:params.spokenPrompt??params.prompt,correctAnswer:params.correctAnswer,acceptedAnswers:params.acceptedAnswers??[params.correctAnswer],explanation:params.explanation,answerChoices:[],inputType:params.inputType??'keypad',tags:[`subject:${params.subject}`,`difficulty:${params.difficulty}`,...params.tags],metadata:params.metadata??{},source:params.source??'new'};return{...q,answerChoices:generateAnswerChoices(q)}}
function numericQuestion(random:Random,seed:string,subject:SubjectId,difficulty:Difficulty,prompt:string,answer:number,explanation:string,tags:string[],metadata:Record<string,number|string|boolean>={},source:QuestionSource='new'){return buildQuestion({seed,subject,difficulty,prompt,correctAnswer:String(answer),explanation,tags,metadata,inputType:random.bool()?'multipleChoice':'keypad',source});}
function generateAddition(r:Random,s:string,d:Difficulty,src:QuestionSource){const max=rangeByDifficulty(d,12,60,220),a=r.int(d==='advanced'?35:2,max),b=r.int(2,d==='beginner'?9:rangeByDifficulty(d,40,80,95)),ans=a+b,c=(a%10)+(b%10)>=10;return numericQuestion(r,s,'addition',d,`${a} + ${b} = ?`,ans,`${a} plus ${b} equals ${ans}.`,c?['operation:addition','skill:carrying']:['operation:addition'],{a,b},src)}
function generateSubtraction(r:Random,s:string,d:Difficulty,src:QuestionSource){const neg=d==='advanced'&&r.next()<.25,a=r.int(d==='beginner'?8:20,rangeByDifficulty(d,30,99,250)),b=r.int(2,rangeByDifficulty(d,9,80,160)),l=neg?Math.min(a,b):Math.max(a,b),rr=neg?Math.max(a,b):Math.min(a,b),ans=l-rr,borrow=(l%10)<(rr%10);return numericQuestion(r,s,'subtraction',d,`${l} - ${rr} = ?`,ans,`${l} minus ${rr} equals ${ans}.`,borrow?['operation:subtraction','skill:borrowing']:['operation:subtraction'],{left:l,right:rr},src)}
function generateMultiplication(r:Random,s:string,d:Difficulty,src:QuestionSource){const a=d==='beginner'?r.pick([2,3,4,5,10]):r.int(2,d==='intermediate'?12:18),b=d==='advanced'?r.int(6,25):r.int(2,d==='beginner'?10:12),ans=a*b;return numericQuestion(r,s,'multiplication',d,`${a} x ${b} = ?`,ans,`${a} times ${b} equals ${ans}.`,['operation:multiplication',`factor:${a}`,`factor:${b}`],{a,b},src)}
function generateDivision(r:Random,s:string,d:Difficulty,src:QuestionSource){const divisor=r.int(2,d==='beginner'?10:12),q=r.int(2,rangeByDifficulty(d,10,15,30)),dividend=divisor*q;return numericQuestion(r,s,'division',d,`${dividend} / ${divisor} = ?`,q,`${dividend} divided by ${divisor} equals ${q}.`,['operation:division',`factor:${divisor}`],{dividend,divisor,quotient:q},src)}
function generateTimesTables(r:Random,s:string,d:Difficulty,src:QuestionSource){const tables=d==='beginner'?[2,5,10]:d==='intermediate'?[3,4,6,8]:[7,9,11,12],a=r.pick(tables),b=r.int(1,12),ans=a*b;return numericQuestion(r,s,'timesTables',d,`${a} x ${b} = ?`,ans,`${a} times ${b} equals ${ans}.`,['operation:multiplication','skill:times-table',`table:${a}`],{a,b},src)}
function generateDecimals(r:Random,s:string,d:Difficulty,src:QuestionSource){const scale=d==='beginner'?10:100,a=r.int(1,d==='beginner'?9:150),b=r.int(1,d==='advanced'?90:70),sign=r.bool()?1:-1,ansScaled=sign>0?a+b:Math.max(a,b)-Math.min(a,b),left=sign>0?a:Math.max(a,b),right=sign>0?b:Math.min(a,b),op=sign>0?'+':'-',ans=ansScaled/scale,prompt=`${left/scale} ${op} ${right/scale} = ?`;return buildQuestion({seed:s,subject:'decimals',difficulty:d,prompt,correctAnswer:String(ans),acceptedAnswers:[String(ans),ans<1&&ans>-1?String(ans).replace('0','.'):String(ans)],explanation:`Use place value: ${prompt.replace('?',String(ans))}`,tags:['operation:decimal','skill:place-value'],metadata:{left,right,scale,operator:op},inputType:'keypad',source:src})}
function generateFractions(r:Random,s:string,d:Difficulty,src:QuestionSource){const denoms=d==='beginner'?[2,3,4,5,8]:[3,4,5,6,8,10,12];if(d!=='beginner'&&r.bool()){const left:Fraction={numerator:r.int(1,7),denominator:r.pick(denoms)},right:Fraction={numerator:r.int(1,7),denominator:r.pick(denoms)},lt=formatFraction(left),rt=formatFraction(right),ans=compareFractions(left,right)>=0?lt:rt;return buildQuestion({seed:s,subject:'fractions',difficulty:d,prompt:`Which is larger: ${lt} or ${rt}?`,spokenPrompt:`Which is larger, ${lt} or ${rt}?`,correctAnswer:ans,explanation:`Compare by using common denominators. ${ans} is larger.`,tags:['operation:fraction','skill:fraction-comparison'],metadata:{left:lt,right:rt},inputType:'multipleChoice',source:src})}const denominator=r.pick(denoms),a=r.int(1,Math.max(1,denominator-1)),b=r.int(1,Math.max(1,denominator-a)),answer=simplifyFraction({numerator:a+b,denominator}),answerText=formatFraction(answer);return buildQuestion({seed:s,subject:'fractions',difficulty:d,prompt:`${a}/${denominator} + ${b}/${denominator} = ?`,spokenPrompt:`${a} over ${denominator} plus ${b} over ${denominator} equals what?`,correctAnswer:answerText,acceptedAnswers:[answerText,`${a+b}/${denominator}`],explanation:`Same denominator: add ${a} + ${b}, then simplify to ${answerText}.`,tags:['operation:fraction',`denominator:${denominator}`],metadata:{a,b,denominator},inputType:'multipleChoice',source:src})}
function generatePercentages(r:Random,s:string,d:Difficulty,src:QuestionSource){const ps=d==='beginner'?[10,25,50,75,100]:d==='intermediate'?[5,10,20,25,30,40,50]:[5,10,15,20,25,30,40,50,75],percent=r.pick(ps),base=r.int(2,d==='advanced'?30:20)*10,ans=percent*base/100;return numericQuestion(r,s,'percentages',d,`${percent}% of ${base} = ?`,ans,`${percent}% of ${base} equals ${ans}.`,['operation:percentage',`percent:${percent}`],{percent,base},src)}
function generateNegativeNumbers(r:Random,s:string,d:Difficulty,src:QuestionSource){const a=r.int(-12,d==='advanced'?12:10),b=r.int(-9,d==='advanced'?12:9),mul=d==='advanced'&&r.bool(),ans=mul?a*b:a+b,op=mul?'x':'+';return numericQuestion(r,s,'negativeNumbers',d,`${a} ${op} ${b} = ?`,ans,`${a} ${op==='x'?'times':'plus'} ${b} equals ${ans}.`,mul?['operation:multiplication','skill:sign-rules']:['operation:addition','skill:crossing-zero'],{a,b,operator:op},src)}
function generateMissingNumber(r:Random,s:string,d:Difficulty,src:QuestionSource){const op=d==='beginner'?r.pick(['add','multiply'] as const):r.pick(['add','subtract','multiply','divide'] as const);if(op==='add'){const ans=r.int(2,30),b=r.int(2,20);return numericQuestion(r,s,'missingNumber',d,`[blank] + ${b} = ${ans+b}`,ans,`${ans} plus ${b} equals ${ans+b}.`,['operation:addition','skill:missing-number'],{b,total:ans+b},src)}if(op==='subtract'){const ans=r.int(10,60),b=r.int(2,20);return numericQuestion(r,s,'missingNumber',d,`[blank] - ${b} = ${ans-b}`,ans,`${ans} minus ${b} equals ${ans-b}.`,['operation:subtraction','skill:missing-number'],{b,result:ans-b},src)}if(op==='divide'){const ans=r.int(2,12),divisor=r.int(2,12);return numericQuestion(r,s,'missingNumber',d,`[blank] / ${divisor} = ${ans}`,ans*divisor,`${ans*divisor} divided by ${divisor} equals ${ans}.`,['operation:division','skill:missing-number'],{divisor,answer:ans},src)}const ans=r.int(2,12),b=r.int(2,12);return numericQuestion(r,s,'missingNumber',d,`${b} x [blank] = ${ans*b}`,ans,`${b} times ${ans} equals ${ans*b}.`,['operation:multiplication','skill:missing-number',`factor:${b}`],{b,product:ans*b},src)}
function generateSquaresRoots(r:Random,s:string,d:Difficulty,src:QuestionSource){const max=rangeByDifficulty(d,10,12,20),root=r.int(2,max);if(d!=='beginner'&&r.bool()){const sq=root*root;return numericQuestion(r,s,'squaresRoots',d,`sqrt(${sq}) = ?`,root,`The square root of ${sq} is ${root}.`,['operation:root','skill:perfect-square'],{root,square:sq},src)}const ans=root*root;return numericQuestion(r,s,'squaresRoots',d,`${root}^2 = ?`,ans,`${root} squared equals ${ans}.`,['operation:square','skill:perfect-square'],{root},src)}
function generateMixed(r:Random,s:string,d:Difficulty,src:QuestionSource):Question{const beg:SubjectId[]=['addition','subtraction','multiplication','division'],inter:SubjectId[]=[...beg,'decimals','fractions','percentages'],adv:SubjectId[]=[...inter,'negativeNumbers','missingNumber','squaresRoots'],pool=d==='beginner'?beg:d==='intermediate'?inter:adv,subject=r.pick(pool),q=generateBySubject(subject,r,`${s}-${subject}`,d,src);return{...q,subject:'mixed' as SubjectId,tags:['subject:mixed',...q.tags.filter(t=>t!=='subject:mixed')]}}
function generateBySubject(subject:SubjectId,r:Random,s:string,d:Difficulty,src:QuestionSource):Question{switch(subject){case'addition':return generateAddition(r,s,d,src);case'subtraction':return generateSubtraction(r,s,d,src);case'multiplication':return generateMultiplication(r,s,d,src);case'division':return generateDivision(r,s,d,src);case'timesTables':return generateTimesTables(r,s,d,src);case'mixed':return generateMixed(r,s,d,src);case'decimals':return generateDecimals(r,s,d,src);case'fractions':return generateFractions(r,s,d,src);case'percentages':return generatePercentages(r,s,d,src);case'negativeNumbers':return generateNegativeNumbers(r,s,d,src);case'missingNumber':return generateMissingNumber(r,s,d,src);case'squaresRoots':return generateSquaresRoots(r,s,d,src);default:return generateAddition(r,s,d,src)}}
export function generateQuestion(subject:SubjectId,difficulty:Difficulty,options:GenerateOptions={}):Question{const seed=options.seed??makeSeed(subject),r=createRandom(`${seed}-${subject}-${difficulty}-${options.level??1}`);return generateBySubject(subject,r,seed,difficulty,options.source??'new')}
export function generateQuestionSet(subject:SubjectId,difficulty:Difficulty,count:number,seedPrefix:string,source:QuestionSource='new'):Question[]{return Array.from({length:count},(_,index)=>generateQuestion(subject,difficulty,{seed:`${seedPrefix}-${index}`,source,level:difficultyRank[difficulty]}))}
export function generateAnswerChoices(question:Question):string[]{const r=createRandom(`${question.seed}-choices`),choices=new Set<string>([question.correctAnswer]),n=Number(question.correctAnswer);if(Number.isFinite(n)){const ds=[1,-1,2,-2,5,-5,10,-10];while(choices.size<4){const c=n+r.pick(ds);if(c!==n&&Number.isFinite(c))choices.add(String(Number(c.toFixed(2))))}}else if(question.correctAnswer.includes('/')){const denoms=[2,3,4,5,6,8,10,12];while(choices.size<4)choices.add(formatFraction({numerator:r.int(1,9),denominator:r.pick(denoms)}))}else{const opts=[...question.acceptedAnswers,'1/2','3/4','2/3','5/8','7/8'];while(choices.size<4)choices.add(r.pick(opts))}return[...choices].sort(()=>r.next()-.5)}
export function questionFromMistake(m:Question,seed:string):Question{return{...m,id:`mistake-${m.id}-${seed}`,seed,source:'mistakeExact',answerChoices:generateAnswerChoices({...m,seed})}}
export { subjectIds };
