import * as SQLite from 'expo-sqlite';
import { AppSettings, DailyMission, GameRoundResult, MistakeItem, StoredAppData, UserProgress } from '../../types';
import { createDefaultStoredData } from '../progress/defaults';
import { ensureDailyMission, markMistakeImprovedInData, recordRoundResult as recordRound } from '../progress/progress';
const databaseName='numbit.db',dataKey='stored-app-data',maxRoundHistory=1000; let cachedData:StoredAppData|null=null;
async function openDatabase(){return SQLite.openDatabaseAsync(databaseName)}
async function ensureSchema(){const db=await openDatabase();await db.execAsync('CREATE TABLE IF NOT EXISTS app_kv (key TEXT PRIMARY KEY NOT NULL, value TEXT NOT NULL, updated_at INTEGER NOT NULL);');return db}
function sanitizeData(value:unknown):StoredAppData{const defaults=createDefaultStoredData();if(!value||typeof value!=='object')return defaults;const parsed=value as Partial<StoredAppData>,savedProgress=parsed.progress??defaults.progress,savedSettings=parsed.settings??defaults.settings;return ensureDailyMission({progress:{...defaults.progress,...savedProgress,topicStats:{...defaults.progress.topicStats,...(savedProgress.topicStats??{})},weeklyActivity:Array.isArray(savedProgress.weeklyActivity)&&savedProgress.weeklyActivity.length===7?savedProgress.weeklyActivity:defaults.progress.weeklyActivity},mistakes:Array.isArray(parsed.mistakes)?parsed.mistakes:defaults.mistakes,roundHistory:Array.isArray(parsed.roundHistory)?parsed.roundHistory.slice(0,maxRoundHistory):defaults.roundHistory,settings:{...defaults.settings,...savedSettings},dailyMission:{...defaults.dailyMission,...(parsed.dailyMission??{})}})}
async function loadData():Promise<StoredAppData>{if(cachedData)return cachedData;try{const db=await ensureSchema();const row=await db.getFirstAsync<{value:string}>('SELECT value FROM app_kv WHERE key = ?',[dataKey]);cachedData=sanitizeData(row?.value?JSON.parse(row.value):null)}catch{cachedData=createDefaultStoredData()}return cachedData}
async function persistData(data:StoredAppData):Promise<StoredAppData>{cachedData=ensureDailyMission({...data,roundHistory:data.roundHistory.slice(0,maxRoundHistory)});const db=await ensureSchema();await db.runAsync('INSERT OR REPLACE INTO app_kv (key, value, updated_at) VALUES (?, ?, ?)',[dataKey,JSON.stringify(cachedData),Date.now()]);return cachedData}
export async function getStoredAppData(){return loadData()} export async function saveStoredAppData(data:StoredAppData){return persistData(data)} export async function getUserProgress():Promise<UserProgress>{return(await loadData()).progress} export async function saveUserProgress(progress:UserProgress):Promise<UserProgress>{const data=await loadData();await persistData({...data,progress});return progress} export async function resetUserProgress(){const current=await loadData(),defaults=createDefaultStoredData();return persistData({...defaults,settings:current.settings})} export async function recordRoundResult(roundResult:GameRoundResult){const data=await loadData();return persistData(recordRound(data,roundResult))} export async function getMistakes():Promise<MistakeItem[]>{return(await loadData()).mistakes} export async function saveMistake(mistake:MistakeItem){const data=await loadData();return persistData({...data,mistakes:[mistake,...data.mistakes]})} export async function markMistakeImproved(mistakeId:string){const data=await loadData();return persistData(markMistakeImprovedInData(data,mistakeId))} export async function getDailyMission():Promise<DailyMission|undefined>{return(await loadData()).dailyMission} export async function saveDailyMission(mission:DailyMission){const data=await loadData();return persistData({...data,dailyMission:mission})} export async function getSettings():Promise<AppSettings>{return(await loadData()).settings} export async function saveSettings(settings:AppSettings){const data=await loadData();return persistData({...data,settings})}
